### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by isometriks** [symedit/SymEdit#14]
Add a way to add in breadcrumbs in the routing:

``` yaml
some_route:
    defaults:
        _symedit:
            breadcrumb: $resource.fullName
```

This would be on the TeamController for instance.
