### ISSUE TITLE
Add configuration options that gives you a chain of properties to use      as the SEO

### ISSUE THREAD

**Issue by isometriks** [symedit/SymEdit#2]
- Add configuration options that gives you a chain of properties to use
   as the SEO:

``` yaml
     SymEdit\Bundle\BlogBundle\Model\PostInterface:
         title:
             - title
         description:
             - summary
             - content
```
