### ISSUE TITLE
Base theme

### ISSUE THREAD

**Issue by isometriks** [symedit/SymEdit#32]
Loop before the last loop with a base theme. Theme should be optional. This is good for making child themes on top of another theme. Base theme = starter theme and then put customizations in the active theme! What to do with theme assets? Maybe some kind of parent or base include?

``` yaml
Stylesheets:
    Inputs:
        - $base
        - bootstrap.min.css
```

Idk... Maybe use the configuration to merge them??
