### ISSUE TITLE
SEO Events and API

### ISSUE THREAD

**Issue by isometriks** [symedit/SymEdit#49]
Do we really want SEO to be calculated during API requests? Probably not, at the least it should be optional. Maybe have a rule like FOSRest that says like:

``` yaml
paths:
    - ^/api
formats:
    - text/html
```

So we only calculate or care about SEO when it's a request to a page. Could even check the format of the request, only generate it if it's asking for HTML. That could be another option besides paths.
