### ISSUE TITLE
Content Types

### ISSUE THREAD

**Issue by isometriks** [symedit/SymEdit#8]
``` yaml
symedit:
    content_types:
        post: SymEdit\Bundle\BlogBundle\Model\PostInterface
        page: SymEdit\Bundle\CoreBundle\Model\PageInterface
```

So this would enable us to do stuff like choose content types for widgets, maybe be like type:post as one of the lines. This could be taken from the _subject or whatever it is to see what the current node is.

Also, we can use prependExtension() or whatever it is, so in the Blog Bundle you would prepend the config for the post content type, in the events you would prepend the event type. If somebody overrode those they wouldn't matter. Beautiful.
